/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'tk' at '12/4/16 10:05 PM' with Gradle 3.2.1
 *
 * @author tk, @date 12/4/16 10:05 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
